### ISSUE TITLE
How to Display/Interact? :)

### ISSUE THREAD

**Issue by ghost** [svenstaro/zombenum#3]
Perhaps this is a bug I'm accidentally finding, or a missing dependency, or something.. but when I compile and run this, it just runs silently, indefinitely, until I cancel it. It does use CPU cycles though, it comes up on `top` at 50-70% CPU use.

No CLI output, and no GUI, appear.

So, am I missing something, or is it supposed to be showing me an SDL window? :)

**Comment by svenstaro** [comment]
Haha, I didn't think anybody would discover it. There is no graphical output right now! It's just a headless simulation for now. I might get back hacking on this soon!
